# Generated by Django 3.2.13 on 2022-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220502_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='number',
            new_name='bill_number',
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
